image: maven:latest
deploy:
  script:
    - 'mvn deploy -s ci_settings.xml'
  only:
    - master

cache:
  # Required to keep artifacts from old builds, e.g. from master
  paths:
    - public
build:
  script: "mvn clean package"
  artifacts:
    name: "ItemMods"
    paths:
      - "target/*.jar"
pages:
  when: always
  image: "openkbs/jdk-mvn-py3"
  before_script:
    - 'sudo pip install mkdocs'
    - 'sudo pip install mkdocs-material'
    - 'sudo pip install pygments'
  script:
    - 'mkdir -p public'
    - 'mkdir -p public/apidocs'
    - 'mkdir -p public/apidocs/$CI_COMMIT_REF_NAME/'
    - 'mv assets docs'
    - 'mv ./*.md docs'
    - 'mkdocs build'
    - 'mv site/* public'
    - 'mvn javadoc:javadoc'
    - 'mv target/site/apidocs/* public/apidocs/$CI_COMMIT_REF_NAME/'
  only:
    - master
  artifacts:
    name: "$CI_PIPELINE_ID"
    paths:
      - public