image: maven:latest

stages:
  - pre
  - test
  - publish
download:
  image: ubuntu:latest
  stage: pre
  script:
    - 'rm -f -R lib'
    - 'apt-get update'
    - 'apt-get install -y wget'
    - 'mkdir lib'
    - 'wget -O lib/spigot-1.16.1.jar https://cdn.getbukkit.org/spigot/spigot-1.16.1.jar'
    - 'wget -O lib/spigot-1.15.2.jar https://cdn.getbukkit.org/spigot/spigot-1.15.2.jar'
    - 'wget -O lib/spigot-1.14.4.jar https://cdn.getbukkit.org/spigot/spigot-1.14.4.jar'
    - 'wget -O lib/spigot-1.13.2.jar https://cdn.getbukkit.org/spigot/spigot-1.13.2.jar'
deploy:
  stage: publish
  script:
    - 'mvn deploy -s ci_settings.xml'
  only:
    - master

cache:
  # Required to keep artifacts from old builds, e.g. from master
  paths:
    - public/com.github.codedoctorde.api
    - lib
build:
  stage: test
  script:
    - "mvn clean compile package"
  artifacts:
    name: "ItemMods"
    paths:
      - "target/*.jar"
  cache:
    paths:
      - lib/
pages:
  stage: publish
  when: always
  image: "openkbs/jdk-mvn-py3:v1.2.2"
  before_script:
    - 'sudo pip install mkdocs'
    - 'sudo pip install mkdocs-material'
    - 'sudo pip install pygments'
  script:
    - 'mkdir -p public'
    - 'mkdir -p public/com.github.codedoctorde.api'
    - 'mkdir -p public/com.github.codedoctorde.api/$CI_COMMIT_REF_NAME/'
    - 'mkdir -p public/com.github.codedoctorde.api/$CI_COMMIT_SHA_NAME/'
    - 'mv assets docs'
    - 'mv ./*.md docs'
    - 'mkdocs build'
    - 'mv site public'
    - 'mvn javadoc:javadoc'
    - 'cp -r target/site/* public/com.github.codedoctorde.api/$CI_COMMIT_REF_NAME/'
    - 'cp -r target/site/* public/com.github.codedoctorde.api/$CI_COMMIT_SHA/'
  only:
    - master
  artifacts:
    name: "$CI_PIPELINE_ID"
    paths:
      - public