image: maven:latest

stages:
  - test
  - publish
deploy:
  stage: test
  script:
    - 'mvn deploy -s ci_settings.xml'
  only:
    - master

cache:
  # Required to keep artifacts from old builds, e.g. from master
  paths:
    - public/api
build:
  stage: test
  script: "mvn clean package"
  artifacts:
    name: "ItemMods"
    paths:
      - "target/*.jar"
pages:
  stage: publish
  when: always
  image: "openkbs/jdk-mvn-py3"
  before_script:
    - 'sudo pip install mkdocs'
    - 'sudo pip install mkdocs-material'
    - 'sudo pip install pygments'
  script:
    - 'mkdir -p public'
    - 'mkdir -p public/api'
    - 'mkdir -p public/api/$CI_COMMIT_REF_NAME/'
    - 'mv assets docs'
    - 'mv ./*.md docs'
    - 'mkdocs build'
    - 'mv site/* public'
    - 'mvn javadoc:javadoc'
    - 'mv target/site/* public/api/$CI_COMMIT_REF_NAME/'
  only:
    - master
  artifacts:
    name: "$CI_PIPELINE_ID"
    paths:
      - public