site_name: CodeDoctorAPI
site_url: https://codedoctorde.gitlab.io/codedoctorapi
repo_url: https://gitlab.com/codedoctorde/codedoctorapi/
theme:
  name: material
markdown_extensions:
  - codehilite
nav:
  - Home: README.md