site_name: CodeDoctorAPI
site_url: https://codedoctorde.github.io/codedoctorapi
repo_url: https://github.com/codedoctorde/codedoctorapi/
theme:
  name: material
markdown_extensions:
  - codehilite
nav:
  - Home: README.md